# Generated by Django 3.2.7 on 2022-03-15 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbefore',
            name='a',
        ),
        migrations.AddField(
            model_name='projectbefore',
            name='AcID',
            field=models.ManyToManyField(blank=True, related_name='AcID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbefore',
            name='status',
            field=models.BooleanField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectAfter',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, choices=[('OnGoing', 'OnGoing'), ('Complete', 'Complete')], max_length=100)),
                ('projectname', models.CharField(max_length=150)),
                ('projectmanager', models.CharField(max_length=150)),
                ('article', models.CharField(max_length=1500)),
                ('AccID', models.ManyToManyField(blank=True, related_name='AccID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
