# Generated by Django 3.2.7 on 2022-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220315_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('projectcommented', models.ManyToManyField(blank=True, related_name='projectcommented', to='project.ProjectAfter')),
            ],
        ),
    ]
