# Generated by Django 3.2.7 on 2022-03-15 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectafter',
            name='AccID',
        ),
        migrations.RemoveField(
            model_name='projectbefore',
            name='AcID',
        ),
        migrations.AddField(
            model_name='projectafter',
            name='StudentID',
            field=models.ManyToManyField(blank=True, related_name='StudentID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectafter',
            name='TeacherID',
            field=models.ManyToManyField(blank=True, related_name='TeacherID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbefore',
            name='PreStudentID',
            field=models.ManyToManyField(blank=True, related_name='PreStudentID', to=settings.AUTH_USER_MODEL),
        ),
    ]
