# Generated by Django 3.2.6 on 2022-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220315_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbefore',
            name='status',
            field=models.CharField(default='Unapprove', max_length=100),
        ),
    ]
