# Generated by Django 3.2.7 on 2022-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectbefore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectafter',
            name='status',
            field=models.CharField(default='OnGoing', max_length=100),
        ),
    ]
